- job:
    name: ui-cookiecutter-tox-checkbuild
    parent: tox
    pre-run: playbooks/checkbuild/pre.yaml
    post-run: playbooks/checkbuild/post.yaml
    vars:
      tox_envlist: checkbuild
      ensure_global_symlinks: true
      # node_version should match the default nodejs version
      # used in horizon nodejs jobs.
      node_version: 14
      # It should match the python version in tox.ini in the template
      python_version: 3.9
- project:
    check:
      jobs:
        - ui-cookiecutter-tox-checkbuild
    gate:
      jobs:
        - ui-cookiecutter-tox-checkbuild
